a = eval(input("nhập giá trị a:"))
b = eval(input("nhập giá trị b:"))
c = eval(input("nhập giá trị c:"))
d = eval(input("nhập giá trị d:"))
max_value = max(a, b, c, d)
min_value = min(a, b, c, d)
print("đây là số lớn nhất:", max_value)
print("đây là số nhỏ nhất:", min_value)